services:

  postgres:
    container_name: postgres
    build:
      # build from Dockerfile
      dockerfile: psql.dockerfile
      #FROM postgres:latest
      #---build args: PGTAG=11
      #POSTGRES_DB:shopdb
      #POSTGRES_USER:postgres
      #POSGRES_PASSWORD:postgres
      #run options -m 500M —kernel-memory 50M —restart always
    volumes:
      - /D/_Projects/javaRepo/shopAccountingSystem/mounts/postgres:/var/lib/postgresql/data
    networks:
      - dbnet
    restart: always
    ports:
      - "15000:5432"
    environment:
      POSTGRES_DB: "shopdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  spring:
    container_name: spring-boot
    depends_on:
      - postgres
    build:
      # build from Dockerfile
      dockerfile: spring.dockerfile
      #FROM openjdk:17
      #COPY . /app
      #WORKDIR /app
      #ENTRYPOINT ["java", "-jar", "/target/shopAccountingSystem-0.0.1-SNAPSHOT.jar"]
    volumes:
      - /app
    networks:
      - dbnet
    restart: always
    ports:
      - "15001:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/shopdb"

  pgadmin:
    container_name: pgadmin
    depends_on:
      - postgres
    image: dpage/pgadmin4:8 #major 8.x
    volumes:
      - /D/_Projects/javaRepo/shopAccountingSystem/mounts/pgadmin:/var/lib/pgadmin
    links:
      - "postgres:postgres"
    networks:
      - dbnet
    restart: always
    ports:
      - "15002:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin

networks:
  dbnet:
    driver: bridge

volumes:
  postgres:
  spring:
  pgadmin: